spring:
  application:
    name: "discovery-server"
#  security:
#    user:
#      name: eureka
#      password: password

server:
  port: 8761

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

